<a href="https://colab.research.google.com/github/Prabhjotbh/DE_lab_2024/blob/main/Prabhjot_A2_60_LAB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("travel-times.csv")

In [ ]:
df

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Comments
0,01-06-2012,16:37,Friday,Home,#NAME?,127.4,78.3,84.8,NaN,39.3,36.3,No,NaN
1,01-06-2012,08:20,Friday,GSK,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No,NaN
2,01-04-2012,16:17,Wednesday,Home,51.27,127.4,82.0,85.8,NaN,37.5,NaN,No,NaN
3,01-04-2012,07:53,Wednesday,GSK,49.17,132.3,74.2,NaN,NaN,39.8,35.6,No,NaN
4,01-03-2012,18:57,Tuesday,Home,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,7/18/2011,08:09,Monday,GSK,54.52,125.6,49.9,82.4,7.89,65.5,NaN,No,NaN
201,7/14/2011,08:03,Thursday,GSK,50.9,123.7,76.2,95.1,7.89,40.1,32.1,Yes,NaN
202,7/13/2011,17:08,Wednesday,Home,51.96,132.6,57.5,NaN,NaN,54.2,40.6,Yes,NaN
203,07-12-2011,17:51,Tuesday,Home,53.28,125.8,NaN,87.6,NaN,51.9,36.5,Yes,NaN
204,07-11-2011,16:56,Monday,Home,51.73,125.0,62.8,92.5,NaN,49.5,33.6,Yes,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            205 non-null    object
 1   StartTime       205 non-null    object
 2   DayOfWeek       205 non-null    object
 3   GoingTo         205 non-null    object
 4   Distance        195 non-null    object
 5   MaxSpeed        198 non-null    float64
 6   AvgSpeed        200 non-null    float64
 7   AvgMovingSpeed  199 non-null    float64
 8   FuelEconomy     181 non-null    float64
 9   TotalTime       200 non-null    float64
 10  MovingTime      199 non-null    float64
 11  Take407All      204 non-null    object
 12  Comments        23 non-null     object
dtypes: float64(6), object(7)
memory usage: 20.9+ KB

In [ ]:
df.shape

(205, 13)

In [ ]:
df.describe()

,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime
count,198.000000,200.000000,199.000000,181.000000,200.000000,199.000000
mean,127.625758,74.554000,82.083417,8.711215,41.656000,37.675879
std,4.124323,11.382049,10.226154,0.524314,7.470092,5.576223
min,112.200000,38.100000,50.300000,7.810000,0.000000,0.000000
25%,124.900000,68.975000,76.650000,8.370000,38.400000,35.600000
50%,127.400000,74.000000,81.400000,8.540000,41.200000,37.600000
75%,129.800000,79.950000,86.250000,9.080000,44.400000,39.900000
max,140.900000,107.700000,112.100000,10.050000,82.300000,62.400000

In [ ]:
df.isnull().count()

Date              205
StartTime         205
DayOfWeek         205
GoingTo           205
Distance          205
MaxSpeed          205
AvgSpeed          205
AvgMovingSpeed    205
FuelEconomy       205
TotalTime         205
MovingTime        205
Take407All        205
Comments          205
dtype: int64

In [ ]:
df.isnull().sum()

Date                0
StartTime           0
DayOfWeek           0
GoingTo             0
Distance           10
MaxSpeed            7
AvgSpeed            5
AvgMovingSpeed      6
FuelEconomy        24
TotalTime           5
MovingTime          6
Take407All          1
Comments          182
dtype: int64

Dropping column with more than 10 null values

In [ ]:
df.dropna(axis=1,thresh=190)

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,TotalTime,MovingTime,Take407All
0,01-06-2012,16:37,Friday,Home,#NAME?,127.4,78.3,84.8,39.3,36.3,No
1,01-06-2012,08:20,Friday,GSK,51.63,130.3,81.8,88.9,37.9,34.9,No
2,01-04-2012,16:17,Wednesday,Home,51.27,127.4,82.0,85.8,37.5,NaN,No
3,01-04-2012,07:53,Wednesday,GSK,49.17,132.3,74.2,NaN,39.8,35.6,No
4,01-03-2012,18:57,Tuesday,Home,51.15,136.2,83.4,88.1,36.8,34.8,No
...,...,...,...,...,...,...,...,...,...,...,...
200,7/18/2011,08:09,Monday,GSK,54.52,125.6,49.9,82.4,65.5,NaN,No
201,7/14/2011,08:03,Thursday,GSK,50.9,123.7,76.2,95.1,40.1,32.1,Yes
202,7/13/2011,17:08,Wednesday,Home,51.96,132.6,57.5,NaN,54.2,40.6,Yes
203,07-12-2011,17:51,Tuesday,Home,53.28,125.8,NaN,87.6,51.9,36.5,Yes
204,07-11-2011,16:56,Monday,Home,51.73,125.0,62.8,92.5,49.5,33.6,Yes

Dropping row with more than 5 null values

In [ ]:
df.dropna(axis=0,thresh=5)

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Comments
0,01-06-2012,16:37,Friday,Home,#NAME?,127.4,78.3,84.8,NaN,39.3,36.3,No,NaN
1,01-06-2012,08:20,Friday,GSK,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No,NaN
2,01-04-2012,16:17,Wednesday,Home,51.27,127.4,82.0,85.8,NaN,37.5,NaN,No,NaN
3,01-04-2012,07:53,Wednesday,GSK,49.17,132.3,74.2,NaN,NaN,39.8,35.6,No,NaN
4,01-03-2012,18:57,Tuesday,Home,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,7/18/2011,08:09,Monday,GSK,54.52,125.6,49.9,82.4,7.89,65.5,NaN,No,NaN
201,7/14/2011,08:03,Thursday,GSK,50.9,123.7,76.2,95.1,7.89,40.1,32.1,Yes,NaN
202,7/13/2011,17:08,Wednesday,Home,51.96,132.6,57.5,NaN,NaN,54.2,40.6,Yes,NaN
203,07-12-2011,17:51,Tuesday,Home,53.28,125.8,NaN,87.6,NaN,51.9,36.5,Yes,NaN
204,07-11-2011,16:56,Monday,Home,51.73,125.0,62.8,92.5,NaN,49.5,33.6,Yes,NaN

Replace null with 0

In [ ]:
df['AvgSpeed'].fillna(0,inplace=True)
df['AvgSpeed'].isnull().sum()

0

# Continued on a different dataset

In [ ]:
df=pd.read_csv("city_day.csv")

In [ ]:
df

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,1/1/2015,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,1/2/2015,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,1/3/2015,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,1/4/2015,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,1/5/2015,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,Ahmedabad,10/19/2015,170.52,NaN,15.49,35.22,48.60,NaN,15.49,34.03,53.98,10.76,31.62,4.83,471.0,Severe
289,Ahmedabad,10/20/2015,203.40,NaN,23.03,36.63,59.66,NaN,23.03,94.30,5.36,0.00,0.00,0.00,529.0,Severe
290,Ahmedabad,10/21/2015,92.71,NaN,12.92,30.65,43.57,NaN,12.92,42.08,72.86,13.33,17.97,5.17,NaN,NaN
291,Ahmedabad,10/22/2015,64.66,NaN,4.79,23.83,28.61,NaN,4.79,34.40,24.76,6.24,12.04,2.24,213.0,Poor
292,Ahmedabad,10/23/2015,78.14,NaN,10.58,28.93,39.51,NaN,10.58,44.91,35.56,4.72,8.87,2.28,297.0,Poor

In [ ]:
df.isnull().sum()

City            0
Date            0
PM2.5          29
PM10          293
NO              3
NO2             2
NOx             2
NH3           293
CO              3
SO2             2
O3              2
Benzene         2
Toluene         2
Xylene          2
AQI            42
AQI_Bucket     42
dtype: int64

Imputing with mean

In [ ]:
df['NO'].fillna(df['NO'].mean(), inplace=True)
df['NO'].isnull().sum()

0

Imputing with median

In [ ]:
print(df['NO2'].median())
df['NO2'].fillna(df['NO2'].median(), inplace=True)
print(df['NO2'].isnull().sum())

18.62
0

Imputing with mode

In [ ]:
print(df['NO2'].mode()[0])
df['NOx'].fillna(df['NOx'].mode()[0], inplace=True)
print(df['NOx'].isnull().sum())

14.82
0

In [ ]:
df['CO'].duplicated().sum()

26

In [ ]:
duplicates = df.duplicated(subset='CO', keep=False)

In [ ]:
df_without_dupli=df[~duplicates]
df_without_dupli

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,1/1/2015,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,1/2/2015,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,1/3/2015,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,1/4/2015,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,1/5/2015,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,Ahmedabad,10/19/2015,170.52,NaN,15.49,35.22,48.60,NaN,15.49,34.03,53.98,10.76,31.62,4.83,471.0,Severe
289,Ahmedabad,10/20/2015,203.40,NaN,23.03,36.63,59.66,NaN,23.03,94.30,5.36,0.00,0.00,0.00,529.0,Severe
290,Ahmedabad,10/21/2015,92.71,NaN,12.92,30.65,43.57,NaN,12.92,42.08,72.86,13.33,17.97,5.17,NaN,NaN
291,Ahmedabad,10/22/2015,64.66,NaN,4.79,23.83,28.61,NaN,4.79,34.40,24.76,6.24,12.04,2.24,213.0,Poor
292,Ahmedabad,10/23/2015,78.14,NaN,10.58,28.93,39.51,NaN,10.58,44.91,35.56,4.72,8.87,2.28,297.0,Poor

In [ ]:
df_without_dupli['CO'].duplicated().sum()

0